<template>
  <div class="section-container">
    <div class="content-wrapper" id="contact" style="display: flex">
      <div>
        <header class="section-header">
          <h2>Contact Us</h2>
        </header>
        <p>
          Pet Inn is ....
          Pet Inn is ....
          Pet Inn is ....
          Pet Inn is ....Pet Inn is ....Pet Inn is ....Pet Inn is ....Pet Inn is ....
        </p>
                <p>
          Pet Inn is ....
          Pet Inn is ....
          Pet Inn is ....
          Pet Inn is ....Pet Inn is ....Pet Inn is ....Pet Inn is ....Pet Inn is ....
        </p>
        <p> Pet Inn is ....
          Pet Inn is ....
          Pet Inn is ....
          Pet Inn is ....Pet Inn is ....Pet Inn is ....Pet Inn is ....Pet Inn is ....</p>
      </div>
    </div>
  </div>
</template>
<script></script>
<style>
</style>
